### ISSUE TITLE
后面出错AssertionError: Only output_size=[1, 1] is supported是什么原因呢

### ISSUE THREAD

**Issue by Hu01001** [zergtant/pytorch-handbook#28]
torch1.0和torchvision0.2.1版本

Traceback (most recent call last):
  File "C:/Users/hufan/PycharmProjects/pytorch-handbook-master/chapter4/ss.py", line 29, in <module>
    writer.add_graph(vgg16, (vgg16_input,))
  File "C:\Users\hufan\Anaconda3\Lib\site-packages\tensorboardX\writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "C:\Users\hufan\Anaconda3\Lib\site-packages\tensorboardX\pytorch_graph.py", line 235, in graph
    _optimize_trace(trace, torch.onnx.utils.OperatorExportTypes.ONNX)
  File "C:\Users\hufan\Anaconda3\Lib\site-packages\tensorboardX\pytorch_graph.py", line 175, in _optimize_trace
    trace.set_graph(_optimize_graph(trace.graph(), operator_export_type))
  File "C:\Users\hufan\Anaconda3\Lib\site-packages\tensorboardX\pytorch_graph.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\hufan\Anaconda3\Lib\site-packages\torch\onnx\__init__.py", line 52, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Users\hufan\Anaconda3\Lib\site-packages\torch\onnx\utils.py", line 504, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "C:\Users\hufan\Anaconda3\Lib\site-packages\torch\onnx\symbolic.py", line 89, in wrapper
    return fn(g, *args)
  File "C:\Users\hufan\Anaconda3\Lib\site-packages\torch\onnx\symbolic.py", line 600, in adaptive_avg_pool2d
    assert output_size == [1, 1], "Only output_size=[1, 1] is supported"
AssertionError: Only output_size=[1, 1] is supported

**Comment by laomao0** [comment]
我也遇到了这个问题，不知道是不是torch版本的问题
